Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2023-08, with the labels that each got.

#302 ⬆️ Bump Ops docker images (dependencies)
  services/graylog/docker-compose.yml
  services/jaeger/docker-compose.yml
  services/monitoring/docker-compose.yml.j2
  services/portainer/docker-compose.yml
  services/redis-commander/docker-compose.yml
  services/traefik/docker-compose.yml.j2
Labels: t:enhancement, t:infra-ops, FAST

#301 Bump DCGM Exporter RAM limit to sane level
  services/monitoring/docker-compose.yml.j2
Labels: t:bug, observability

#297 Add RABBIT_SECURE
  services/simcore/template.env
Labels: FAST

#152 Deployment script - pg-backup improvments
  scripts/deployments/deploy.sh
Labels: t:bug, t:enhancement

#303 Remove MAIL service
  .gitignore
  certificates/Makefile
  scripts/deployments/deploy.sh
  services/mail/README.md
  services/mail/config/amavis.cf
  services/mail/docker-compose-aws.yml
  services/mail/docker-compose.aws.yml
  services/mail/docker-compose.local.yml
  services/mail/docker-compose.yml
  services/mail/setup.sh
  services/mail/template.env
Labels: p:low-prio, FAST

#304 🐛 Fix wrong makefile target for graylog on osparc-master
  services/graylog/Makefile
Labels: t:bug, observability, p:high-prio, FAST

#306 ✨ Add docker node resources statistics script
  ci/ciRunsDockerContainer/Dockerfile
  scripts/dockerNodeStats/.gitignore
  scripts/dockerNodeStats/Dockerfile
  scripts/dockerNodeStats/Makefile
  scripts/dockerNodeStats/README.md
  scripts/dockerNodeStats/main.py
  scripts/dockerNodeStats/requirements.txt
Labels: t:enhancement

#309 Extract traefik logs graylog & fix graylog configure
  services/graylog/data/contentpacks/osparc-custom-content-pack-v2.json
  services/graylog/docker-compose.yml
  services/graylog/scripts/configure.py
Labels: t:bug, p:low-prio

#310 BUGFIX: Update traefik extractor pattern
  services/graylog/data/contentpacks/osparc-custom-content-pack-v2.json
Labels: t:bug, p:low-prio, FAST

#312 ✨ Add deployment labels for clusters_keeper microservices
  .pre-commit-config.yaml
  services/simcore/docker-compose.yml
Labels: p:high-prio

#314 ♻️ Add pyenv to CI docker container
  ci/ciRunsDockerContainer/Dockerfile
  ci/ciRunsDockerContainer/Makefile
  ci/ciRunsDockerContainer/template.env
  scripts/dockerNodeStats/Dockerfile
Labels: t:enhancement

#313 Disable vcs check on aws/dalco/public deployment
  Makefile
  scripts/deployments/deploy.sh
Labels: t:bug, FAST

#318 Bugfix add rabbit_secure to autoscaling
  services/simcore/docker-compose.yml
Labels: t:bug, p:mid-prio, FAST

#322 Monitoring / Prometheus fixes: Ceph scraping and simcore container labels
  services/monitoring/Makefile
  services/monitoring/docker-compose.public.yml
  services/monitoring/grafana/provisioning/osparc.io/dashboards/simcore/s4l-lite-admin-overview.json
  services/monitoring/grafana/provisioning/staging.osparc.io/dashboards/simcore/s4l-lite-admin-overview.json
  services/monitoring/grafana/provisioning/tip.itis.swiss/dashboards/simcore/admin-overview.json
  services/monitoring/prometheus/prometheus-base.yml
Labels: t:bug, observability, p:high-prio, t:infra-ops

#329 Add docker resource limits to 20% services
  services/admin-panels/docker-compose.yml.j2
  services/adminer/docker-compose.yml
  services/deployment-agent/docker-compose.yml.j2
  services/filestash/docker-compose.yml
  services/graylog/docker-compose.yml
  services/jaeger/docker-compose.yml
  services/monitoring/prometheus/README.md
  services/pg-backup/docker-compose.yml.j2
  services/redis-commander/docker-compose.yml
Labels: t:enhancement, p:mid-prio, t:infra-ops

#335 Add capture of director-v2 loglevel
  services/simcore/docker-compose.yml
  services/simcore/template.env
Labels: observability, FAST
