Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2023-10, with the labels that each got.

#381 Changes for https://github.com/ITISFoundation/osparc-simcore/pull/4792
  services/simcore/template.env
Labels: FAST

#385 Expose payments service
  scripts/common.Makefile
  services/simcore/docker-compose.yml
  services/simcore/template.env
Labels: p:high-prio

#384 Add memory limits / reservations (:warning: OPS)
  services/monitoring/docker-compose.yml.j2
  services/traefik/docker-compose.yml.j2
Labels: t:enhancement

#391 Remove RFC2136 propagation timeout
  services/traefik/docker-compose.dalco.yml
  services/traefik/docker-compose.public.yml
  services/traefik/template.env
Labels: t:enhancement

#400 Fix payments routing
  services/simcore/docker-compose.yml
Labels: t:bug

#405 Add prepare simcore stack
  scripts/deployments/prepare_simcore_stack.bash
Labels: FAST

#406 Changes for staging_Microhistory4 release
  services/simcore/docker-compose.deploy.local.yml
  services/simcore/docker-compose.deploy.public.yml
  services/simcore/template.env
Labels: p:mid-prio

#411 Fix graylog limits
  services/graylog/docker-compose.yml
Labels: t:bug, FAST

#412 Remove PAYMENTS_AUTORECHARGE_MIN_BALANCE_IN_CREDITS
  services/simcore/template.env
Labels: p:high-prio, FAST
