Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2023-11, with the labels that each got.

#418 Update portainer secret documentation
  services/portainer/Makefile
Labels: FAST

#428 Cleanup housekeeping nov2023
  .gitignore
  .pre-commit-config.yaml
  scripts/deployments/prepare_simcore_stack.bash
  scripts/deployments/start_without_deployment_agent.bash
  scripts/deployments/startup_script.bash
  scripts/pre-commit-hooks/stack-yml-generated-is-valid/launch.bash
  services/deployment-agent/.gitignore
  services/deployment-agent/Makefile
  services/deployment-agent/README.md
  services/deployment-agent/deployment_config.devel.yml
  services/deployment-agent/deployment_config.template.yml
  services/deployment-agent/docker-compose.aws.yml
  services/deployment-agent/docker-compose.devel.yml
  services/deployment-agent/docker-compose.yml.j2
  services/deployment-agent/how_to_create_releases.md
  services/deployment-agent/template.env
  services/monitoring/prometheus/prometheus-base.yml
  services/simcore/docker-compose.yml
Labels: t:enhancement, t:infra-ops

#430 BUGFIX: Graylog cannot parse log_timestamp
  services/graylog/GraylogWorkflow.png
  services/graylog/README.md
  services/graylog/data/contentpacks/osparc-custom-content-pack-v2.json
Labels: t:bug

#431 Auto configure graylog on start
  services/graylog/Makefile
Labels: t:enhancement, FAST

#432 Run pre commit hooks
  CODEOWNERS
  scripts/s3BucketOptions/setBucketCORS.py
  scripts/s3BucketOptions/setBucketLifecyclePolicy.py
  scripts/s3BucketOptions/setBucketLifecyclePolicyCEPH.py
  scripts/s3RobustCopy/main.py
  services/admin-panels/data/ProjectsQuestions.ipynb
  services/batman-panels/main.py
  services/monitoring/grafana/scripts/import.py
  services/pg-backup/README.md
Labels: FAST

#433 Add docker resource limits
  services/monitoring/docker-compose.yml.j2
  services/portainer/docker-compose.yml
  services/registry/docker-compose.yml
  services/traefik/docker-compose.yml.j2
Labels: p:mid-prio

#434 Add ci
  .github/workflows/ci.yml
Labels: p:low-prio, FAST

#436 Remove batman panels
  services/batman-panels/.gitignore
  services/batman-panels/Makefile
  services/batman-panels/README.md
  services/batman-panels/default.conf
  services/batman-panels/default.css
  services/batman-panels/docker-compose.devel.yml
  services/batman-panels/docker-compose.letsencrypt.dns.yml
  services/batman-panels/docker-compose.master.yml
  services/batman-panels/docker-compose.yml
  services/batman-panels/main.py
  services/batman-panels/nginx.conf
  services/batman-panels/requirements.txt
  services/batman-panels/static.j2
  services/batman-panels/template.env
Labels: FAST, refactoring

#437 Add helpers folder
  scripts/helpers/gen_pwd.py
  scripts/helpers/get_unused_aws_key_pairs.py
Labels: p:low-prio, FAST

#442 Introduce PR template
  .github/workflows/PULL_REQUEST_TEMPLATE.md
Labels: p:low-prio, FAST

#443 Fix PR template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/PULL_REQUEST_TEMPLATE.md
Labels: t:bug, FAST

#441 Add: validate simcore stack yml bash script - to be used in CI/CD
  scripts/deployments/validate_simcore_stack_yml.bash
  services/graylog/Makefile
Labels: t:enhancement

#439 ✨ Add: Prometheus Federation 🚧
  scripts/deployments/deploy.sh
  services/monitoring/docker-compose.yml.j2
  services/monitoring/grafana/provisioning/osparc.io/dashboards/simcore/s4l-lite-admin-overview.json
  services/monitoring/grafana/provisioning/tip.itis.swiss/dashboards/simcore/admin-overview.json
  services/monitoring/pgsql_query_exporter_config.yaml.j2
  services/monitoring/prometheus/prometheus-federation.yml
  services/monitoring/prometheus/prometheus-simcore.yml
  services/monitoring/prometheus/prometheus.rules.yml
  services/monitoring/template.env
Labels: t:enhancement, observability, t:infra-ops

#445 Required changes for simcore PR 5043
  services/redis-commander/docker-compose.dalco.yml
  services/redis-commander/docker-compose.yml
Labels: FAST

#452 Fix prometheus catchall deploy constraints
  services/monitoring/docker-compose.master.yml
Labels: t:bug, FAST

#451 PG Backups use local `/backups `
  services/pg-backup/docker-compose.yml.j2
Labels: t:bug, t:enhancement, p:mid-prio

#446 Simcore PR https://github.com/ITISFoundation/osparc-simcore/pull/5051
  scripts/deployments/validate_simcore_stack_yml.bash
Labels: t:bug, t:enhancement

#454 Add Changelog when release-tagging
  Makefile
  scripts/pre-commit-hooks/stack-yml-generated-is-valid/launch.bash
Labels: t:enhancement, FAST

#462 Rename maintenance page stack - make it shorter
  services/maintenance-page/docker-compose.yml.j2
Labels: p:high-prio, FAST
