Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2023-09, with the labels that each got.

#338 Add pipeline to standardize traefik log level (uppercase)
  services/graylog/data/contentpacks/osparc-custom-content-pack-v2.json
Labels: p:low-prio, FAST

#348 :warning: New autoscaling env
  services/simcore/docker-compose.yml
  services/simcore/template.env
Labels: p:high-prio, FAST

#349 Add payments env to webserver
  services/simcore/template.env
Labels: p:high-prio, FAST

#350 Scale to 0 deployment agent
  services/deployment-agent/docker-compose.yml.j2
Labels: p:low-prio, FAST

#357 Docker CI Container Enhancements
  ci/ciRunsDockerContainer/Dockerfile
  ci/ciRunsDockerContainer/template.env
Labels: FAST, e2e & test

#346 Remove duplicated router settings
  services/monitoring/docker-compose.letsencrypt.dns.yml
  services/monitoring/docker-compose.letsencrypt.http.yml
Labels: t:bug, p:mid-prio, FAST

#359 Fix graylog dashboard
  services/graylog/README.md
  services/graylog/data/contentpacks/osparc-custom-content-pack-v2.json
  services/graylog/scripts/README.md
  services/graylog/scripts/configure.py
  services/graylog/scripts/dashboards.yaml
Labels: t:bug, FAST
