Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2023-06, with the labels that each got.

#159 added all the info about .env-wb-db-event-listener
  .gitignore
  scripts/deployments/start_without_deployment_agent.bash
  scripts/pre-commit-hooks/stack-yml-generated-is-valid/launch.bash
  services/deployment-agent/deployment_config.template.yml
  services/deployment-agent/startup_script.bash
  services/simcore/docker-compose.yml
Labels: t:enhancement

#160 Update how_to_create_releases.md
  services/deployment-agent/how_to_create_releases.md
Labels: t:enhancement

#163 Add s4l-lite dashboard to staging.osparc.io
  services/monitoring/grafana/provisioning/staging.osparc.io/dashboards/simcore/s4l-lite-admin-overview.json
Labels: t:enhancement

#164 ✨ Add SmokePing Grafana Dashboard and Prometheus Exporter
  services/monitoring/docker-compose.yml.j2
  services/monitoring/grafana/provisioning/allDeployments/dashboards/ops/SmokePing.json
  services/monitoring/smokeping_prober_config.yaml
Labels: t:enhancement, observability

#167 Remove graylog alert that is not accurate / does not apply anymore
  services/graylog/scripts/alerts.template.yaml
Labels: t:enhancement, observability, alerting

#169 Pin stuff in dockerfile, ensure firefox is not installed via snap
  ci/ciRunsDockerContainer/Dockerfile
  ci/ciRunsDockerContainer/README.md
  ci/ciRunsDockerContainer/mozillateam.pref
  ci/ciRunsDockerContainer/template.env
Labels: t:bug, t:enhancement

#168 Enhancement/smokeping targets per deployment 🚧🚧🚧
  .gitignore
  services/monitoring/Makefile
  services/monitoring/smokeping_prober_config.yaml.j2
  services/monitoring/template.env
Labels: t:enhancement, observability

#170 higher RAM limits on dask scheduler
  services/simcore/docker-compose.yml
Labels: t:enhancement

#178 Bump deployment agent version
  services/deployment-agent/docker-compose.yml.j2
Labels: t:bug

#179 Adds second prometheus
  services/monitoring/docker-compose.aws.yml
  services/monitoring/docker-compose.dalco.yml
  services/monitoring/docker-compose.letsencrypt.dns.yml
  services/monitoring/docker-compose.letsencrypt.http.yml
  services/monitoring/docker-compose.master.yml
  services/monitoring/docker-compose.yml.j2
  services/monitoring/prometheus/prometheus-cadvisor.yml
Labels: t:enhancement, observability

#182 🐛 ⚗️ Faulty prometheus instance names not corresponding to hostnames
  services/monitoring/prometheus/README.md
  services/monitoring/prometheus/prometheus-base.yml
Labels: t:bug, a:infra+ops, observability

#184 🐛 Fix 302 Redirect bug in cadvisor prometheus
  services/monitoring/docker-compose.aws.yml
  services/monitoring/docker-compose.dalco.yml
  services/monitoring/docker-compose.letsencrypt.dns.yml
  services/monitoring/docker-compose.letsencrypt.http.yml
  services/monitoring/docker-compose.master.yml
  services/monitoring/docker-compose.yml.j2
Labels: t:bug, observability

#183 Expose swagger route on invitations service
  scripts/common.Makefile
  services/simcore/docker-compose.yml
Labels: t:enhancement, a:infra+ops

#247 Bump migration RAM to 180MB
  services/simcore/docker-compose.yml
Labels: t:bug, p:high-prio, t:infra-ops

#249 🐛 Fix certificate generation bugs
  services/traefik/Makefile
  services/traefik/docker-compose.letsencrypt.dns.yml.j2
  services/traefik/docker-compose.yml.j2
  services/traefik/template.env
Labels: t:bug, p:high-prio
