Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2023-03, with the labels that each got.

#111 Alerting/docker ip range exhausted
  services/graylog/scripts/alerts.template.yaml
Labels: alerting

#112 Remove extra quotation marks 🚧🚧🚧
  services/graylog/scripts/alerts.template.yaml
Labels: t:bug

#98 Dependency upgrades (🚧🚧🚧)
  services/filestash/docker-compose.yml
  services/graylog/docker-compose.yml
  services/graylog/scripts/configure.py
  services/jaeger/docker-compose.yml
  services/monitoring/docker-compose.yml
  services/portainer/docker-compose.yml
  services/simcore/docker-compose.yml
Labels: dependencies

#116 DevOps Changes for Simcore PR 3937
  services/redis-commander/docker-compose.yml
Labels: a:infra+ops

#119 Upgrade deployment agent patch version
  services/deployment-agent/docker-compose.yml
Labels: t:enhancement

#120 🐛 Fixes pre-commit, shellcheck, curl, docs
  scripts/deployments/deploy.sh
  scripts/pre-commit-hooks/stack-yml-generated-is-valid/launch.bash
  scripts/pre-commit-hooks/stack-yml-generated-is-valid/requirements.txt
  services/monitoring/README.md
  services/pg-backup/docker-compose.yml.j2
Labels: t:bug

#121 ♻️ Prometheus Monitoring Stack Refactoring
  .gitignore
  scripts/migration/db-restore.bash
  scripts/migration/template.env
  services/monitoring/Makefile
  services/monitoring/README.md
  services/monitoring/docker-compose.aws.yml
  services/monitoring/docker-compose.dalco.yml
  services/monitoring/docker-compose.local.yml
  services/monitoring/docker-compose.master.yml
  services/monitoring/docker-compose.yml.j2
  services/monitoring/pgsql_query_exporter_config.yaml.j2
Labels: t:enhancement, observability

#122 ♻️✨ Grafana Monitoring Stack Refactoring
  services/monitoring/grafana/provisioning/allDeployments/alerts/osparc_alerts.json
  services/monitoring/grafana/provisioning/allDeployments/dashboards/nih-metrics/SPARC DRC Metrics.json
  services/monitoring/grafana/provisioning/allDeployments/dashboards/ops/Cardinality Explorer.json
  services/monitoring/grafana/provisioning/allDeployments/dashboards/ops/GPU Nodes.json
  services/monitoring/grafana/provisioning/allDeployments/dashboards/ops/Traefik2.json
  services/monitoring/grafana/provisioning/allDeployments/dashboards/simcore/Metrics.json
  services/monitoring/grafana/provisioning/allDeployments/dashboards/simcore/PostgreSQL Database.json
  services/monitoring/grafana/provisioning/allDeployments/dashboards/simcore/RabbitMQ-Overview.json
  services/monitoring/grafana/provisioning/allDeployments/dashboards/system/Docker Swarm Overview.json
  services/monitoring/grafana/provisioning/allDeployments/dashboards/system/Nodes -  Detailed Insights.json
  services/monitoring/grafana/provisioning/allDeployments/dashboards/system/Nodes - Overview.json
  services/monitoring/grafana/provisioning/osparc-master.speag.com/datasources2dashboards.yaml
  services/monitoring/grafana/provisioning/osparc.io/dashboards/simcore/s4l-lite-admin-overview.json
  services/monitoring/grafana/provisioning/osparc.io/datasources2dashboards.yaml
  services/monitoring/grafana/provisioning/osparc.speag.com/datasources2dashboards.yaml
  services/monitoring/grafana/provisioning/staging.osparc.io/datasources2dashboards.yaml
  services/monitoring/grafana/scripts/import.py
Labels: t:enhancement, observability

#113 Add placement constraint label to rabbitmq
  services/simcore/docker-compose.deploy.aws.yml
  services/simcore/docker-compose.deploy.dalco.yml
  services/simcore/docker-compose.deploy.master.yml
  services/simcore/docker-compose.deploy.public.yml
Labels: a:infra+ops

#123 🔊 Alerting/add grafana alert for logspout swapping
  services/graylog/docker-compose.yml
  services/monitoring/grafana/provisioning/allDeployments/alerts/osparc_alerts.json
  services/monitoring/grafana/scripts/export.py
  services/monitoring/grafana/scripts/import.py
Labels: t:bug, a:infra+ops, alerting

#124 ⬆️ Upgrade: docker compose v1 deprecation
  ci/ciRunsDockerContainer/Makefile
  scripts/deployments/start_without_deployment_agent.bash
  scripts/docker-compose-config.bash
  scripts/pre-commit-hooks/stack-yml-generated-is-valid/.gitignore
  scripts/pre-commit-hooks/stack-yml-generated-is-valid/launch.bash
  scripts/pre-commit-hooks/validateDockerComposeNoDuplication/.gitignore
  scripts/pre-commit-hooks/validateDockerComposeNoDuplication/launch.bash
  services/admin-panels/Makefile
  services/adminer/Makefile
  services/batman-panels/Makefile
  services/deployment-agent/Makefile
  services/deployment-agent/deployment_config.devel.yml
  services/deployment-agent/deployment_config.template.yml
  services/deployment-agent/startup_script.bash
  services/filestash/Makefile
  services/graylog/Makefile
  services/jaeger/Makefile
  services/mail/Makefile
  services/mail/template.env
  services/maintenance-page/Makefile
  services/minio/Makefile
  services/monitoring/Makefile
  services/pg-backup/Makefile
  services/portainer/Makefile
  services/redis-commander/Makefile
  services/registry/Makefile
  services/traefik/Makefile
Labels: t:bug, t:enhancement, a:infra+ops

#125 fix allert message
  services/graylog/scripts/alerts.template.yaml
Labels: alerting

#128 🐛✨ graylog alerting: Fix and Add Alert
  services/graylog/scripts/alerts.template.yaml
  services/graylog/scripts/configure.py
Labels: t:bug, a:infra+ops, alerting

#131 🗑️Remove mailserver automatic starting from aws
  scripts/deployments/deploy.sh
  services/mail/README.md
Labels: a:infra+ops
