Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2023-12, with the labels that each got.

#470 Make S4L admin overview grafana dashboard changes persistant
  scripts/pre-commit-hooks/stack-yml-generated-is-valid/launch.bash
  services/monitoring/grafana/provisioning/osparc.io/dashboards/simcore/s4l-lite-admin-overview.json
  services/simcore/template.env
Labels: observability, FAST

#469 Add dynamic scheduler
  services/simcore/docker-compose.yml
Labels: FAST

#474 Add simcore resource limits
  services/simcore/docker-compose.yml
Labels: t:enhancement, p:mid-prio

#476 Fix db resources
  services/simcore/docker-compose.yml
Labels: t:bug, p:high-prio, FAST

#477 Fix master adminer resources
  services/adminer/docker-compose.master.yml
Labels: t:bug, p:mid-prio, FAST

#478 Use custom certs on Dalco & TIP
  services/admin-panels/Makefile
  services/adminer/Makefile
  services/filestash/Makefile
  services/graylog/Makefile
  services/jaeger/Makefile
  services/minio/Makefile
  services/monitoring/Makefile
  services/portainer/Makefile
  services/redis-commander/Makefile
  services/registry/Makefile
  services/traefik/config/osparc.speag.com_dyn_cfg.yaml
  services/traefik/config/tip.itis.swiss_dyn_cfg.yaml
  services/traefik/docker-compose.dalco.yml
  services/traefik/docker-compose.public.yml
Labels: p:high-prio

#475 ✨ Introduce env-vars to control replication of catalog, director-v0, dask-scheduler
  services/monitoring/grafana/provisioning/osparc-testing.click/datasources2dashboards.yaml
  services/simcore/docker-compose.deploy.local.yml
  services/simcore/docker-compose.yml
Labels: t:enhancement, refactoring

#480 Pull latest docker image in `validate_simcore_stack_yml.bash`
  scripts/deployments/validate_simcore_stack_yml.bash
Labels: t:enhancement, FAST

#481 Traefik cert mgmt per depl
  services/traefik/config/aws_dyn_cfg.yml
  services/traefik/config/dalco_dyn_cfg.yml
  services/traefik/config/local_dyn_cfg.yml
  services/traefik/config/master_dyn_cfg.yml
  services/traefik/config/public_dyn_cfg.yml
  services/traefik/docker-compose.aws.yml
  services/traefik/docker-compose.dalco.yml
  services/traefik/docker-compose.local.yml
  services/traefik/docker-compose.master.yml
  services/traefik/docker-compose.public.yml
Labels: p:high-prio, EPIC

#483 Aws custom certs
  services/admin-panels/Makefile
  services/adminer/Makefile
  services/filestash/Makefile
  services/graylog/Makefile
  services/jaeger/Makefile
  services/maintenance-page/docker-compose.yml.j2
  services/monitoring/Makefile
  services/portainer/Makefile
  services/redis-commander/Makefile
  services/registry/Makefile
  services/simcore/Makefile
  services/traefik/Makefile
  services/traefik/docker-compose.aws.yml
Labels: p:high-prio, FAST

#487 Add API server prometheus scraping
  services/monitoring/prometheus/prometheus-simcore.yml
Labels: p:high-prio, FAST

#489 Add sim4life.io cert path
  services/traefik/config/aws_dyn_cfg.yml
Labels: t:bug, p:high-prio

#490 Auto configure grafana on start
  services/monitoring/Makefile
Labels: p:mid-prio, FAST
