Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2023-01, with the labels that each got.

#81 🐛 Fix/grafana node dashboard for autoscaling
  scripts/common.Makefile
  services/monitoring/Makefile
  services/monitoring/grafana/provisioning/allDeployments/dashboards/system/Nodes -  Detailed Insights.json
Labels: t:bug

#84 Change pg_backup tool version from justb4/pgbackup to kartoza/pg-backup
  services/pg-backup/Makefile
  services/pg-backup/docker-compose.public.yml
  services/pg-backup/docker-compose.yml
  services/pg-backup/docker-compose.yml.j2
  services/pg-backup/template.env
Labels: t:bug, a:infra+ops

#83 ✨Add/testing route works with dynamic services
  Makefile
  scripts/common.Makefile
  services/simcore/Makefile
  services/simcore/docker-compose.deploy.local.yml
  services/simcore/docker-compose.yml
  services/simcore/template.env
  services/traefik/docker-compose.letsencrypt.dns.yml.j2
Labels: t:bug, t:enhancement, a:infra+ops

#85 Divers fix to make pg-backup works on all deployments. ( :warning: )
  services/pg-backup/Makefile
  services/pg-backup/README.md
  services/pg-backup/docker-compose.public.yml
  services/pg-backup/docker-compose.yml.j2
Labels: t:bug

#89 Fix/product cors
  services/traefik/.gitignore
  services/traefik/Makefile
  services/traefik/docker-compose.yml.j2
Labels: t:bug

#86 🐛 Fix: Dont capture service.testing.${MACHINE_FQDN} in maintenance page
  scripts/common.Makefile
  services/maintenance-page/docker-compose.yml
  services/maintenance-page/template.env
Labels: t:bug

#92 🐛 Fix error in call_make call
  scripts/deployments/deploy.sh
  scripts/deployments/start_without_deployment_agent.bash
Labels: t:bug

#93 ✨ Enhancement/html maintenance page per Deployment FQDN🚧🚧🚧
  services/maintenance-page/.gitignore
  services/maintenance-page/Makefile
  services/maintenance-page/docker-compose.yml
  services/maintenance-page/docker-compose.yml.j2
  services/maintenance-page/template.env
Labels: t:enhancement
