Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2023-07, with the labels that each got.

#259 adding RESOURCE_USAGE_TRACKER_HOST
  .python-version
  services/simcore/template.env
Labels: FAST

#270 adding io.simcore labels to prometheus
  services/monitoring/prometheus/prometheus-cadvisor.yml
Labels: t:enhancement, observability

#271 ⬆️ bump smokeping prober minor version
  services/monitoring/docker-compose.yml.j2
Labels: t:enhancement, observability, FAST

#272 🏗️ Changes: Simcore PR4487
  services/redis-commander/docker-compose.dalco.yml
  services/redis-commander/docker-compose.yml
Labels: p:high-prio, t:infra-ops, during maintenance

#281 Make traefik routing priorities for invitation creation higher than swagger API specs
  services/simcore/docker-compose.yml
Labels: t:bug, p:high-prio
