Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2023-05, with the labels that each got.

#149 Fix bad configuration for dns challenge resolver
  services/traefik/docker-compose.public.yml
Labels: t:bug

#150 Prometheus swarm target bug
  services/monitoring/prometheus/prometheus-base.yml
Labels: t:bug

#151 added 2 new alerts
  services/graylog/scripts/alerts.template.yaml
Labels: alerting

#147 Alerting/add grafana alert for high prometheus cardinality
  services/monitoring/grafana/provisioning/allDeployments/alerts/osparc_alerts.json
Labels: observability
