Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2024-01, with the labels that each got.

#491 bumping GC limit, too low
  services/simcore/docker-compose.yml
Labels: t:bug

#492 add API server grafana dashboard
  services/monitoring/grafana/provisioning/allDeployments/dashboards/simcore/ApiServer.json
Labels: observability

#488 Appmotion gateway
  .gitignore
  scripts/common.Makefile
  services/adminer/docker-compose.yml
  services/appmotion_gateway/.gitignore
  services/appmotion_gateway/Makefile
  services/appmotion_gateway/docker-compose.aws.yml
  services/appmotion_gateway/docker-compose.local.yml
  services/appmotion_gateway/docker-compose.yml
  services/appmotion_gateway/template.api_env
  services/appmotion_gateway/template.env
  services/simcore/docker-compose.yml
Labels: p:high-prio

#497 Update graylog limits
  services/graylog/docker-compose.yml
Labels: FAST

#495 Appmotion gw: switch traefik routes
  scripts/common.Makefile
  services/appmotion_gateway/docker-compose.yml
  services/simcore/docker-compose.yml
  services/simcore/template.env
Labels: p:high-prio

#507 🔨 Add more simcore services to Prometheus config
  services/monitoring/prometheus/prometheus-simcore.yml
Labels: observability

#508 Add newly instrumented simcore services to grafana dashboard
  services/monitoring/grafana/provisioning/allDeployments/dashboards/simcore/SimcoreService.json
Labels: observability

#510 🐛 Fix prometheus Failure on TIP
  services/monitoring/Makefile
Labels: t:bug, observability

#509 Minor fixes to simcore service grafana dashboard
  services/monitoring/grafana/provisioning/allDeployments/dashboards/simcore/SimcoreService.json
Labels: observability

#514 ♻️ appmotion-gateway refactoring
  scripts/common.Makefile
  scripts/deployments/deploy.sh
  services/appmotion_gateway/docker-compose.yml
  services/appmotion_gateway/template.env
Labels: t:enhancement, t:infra-ops

#513 Remove `services/simcore/template.env`
  services/simcore/Makefile
  services/simcore/template.env
Labels: t:enhancement, t:infra-ops

#520 Reduce overprovisioned resource reservations
  services/admin-panels/docker-compose.yml.j2
  services/adminer/docker-compose.yml
  services/filestash/docker-compose.yml
  services/jaeger/docker-compose.yml
  services/pg-backup/docker-compose.yml.j2
  services/portainer/docker-compose.yml
  services/redis-commander/docker-compose.yml
  services/registry/docker-compose.yml
Labels: p:high-prio, FAST

#521 Merge `hotifx_staging_ThisIsSparta3` into `main`
  services/appmotion_gateway/docker-compose.aws.yml
Labels: p:high-prio, FAST

#522 Bump storage memory limit
  services/simcore/docker-compose.yml
Labels: t:bug, p:high-prio, FAST

#524 Bump simcore traefik replicas to 2
  services/simcore/docker-compose.yml
Labels: t:enhancement, p:mid-prio, FAST

#525 Add missing DNS config and warning in docker-compose.aws.yml
  services/admin-panels/docker-compose.aws.yml
  services/adminer/docker-compose.aws.yml
  services/appmotion_gateway/docker-compose.aws.yml
  services/filestash/docker-compose.aws.yml
  services/graylog/docker-compose.aws.yml
  services/jaeger/docker-compose.aws.yml
  services/portainer/docker-compose.aws.yml
  services/redis-commander/docker-compose.aws.yml
  services/registry/docker-compose.aws.yml
  services/traefik/docker-compose.aws.yml
Labels: t:bug, p:high-prio, FAST

#526 Add Dask monitoring
  services/monitoring/prometheus/prometheus-simcore.yml
  services/simcore/docker-compose.yml
Labels: t:enhancement

#528 Bump dask resource limits
  services/simcore/docker-compose.yml
Labels: p:mid-prio, FAST

#533 Fix typo in dask-scheduler name
  services/monitoring/prometheus/prometheus-simcore.yml
Labels: FAST

#536 Comp-backend: Ensure dask secrets are relative to stack.yml file
  scripts/deployments/prepare_simcore_stack.bash
Labels: FAST

#537 Fixes ack problem with in appmotion gateway
  services/appmotion_gateway/template.api_env
Labels: p:high-prio

#539 Add dask-sidecar monitoring on top of schedulers
  services/monitoring/prometheus/prometheus-simcore.yml
Labels: FAST
