Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2024-03, with the labels that each got.

#592 Update simcore service grafana dashboards
  services/monitoring/grafana/provisioning/allDeployments/dashboards/simcore/SimcoreService.json
Labels: observability

#590 add rsync to ci docker image - bump version to 0.7.0
  ci/ciRunsDockerContainer/Dockerfile
  ci/ciRunsDockerContainer/template.env
Labels: t:enhancement, FAST, e2e & test

#596 Add endpoint statistics to simcore service dashboard
  ci/ciRunsDockerContainer/Dockerfile
  ci/ciRunsDockerContainer/template.env
  services/monitoring/grafana/provisioning/allDeployments/dashboards/simcore/SimcoreService.json
  services/simcore/docker-compose.yml
Labels: observability

#599 nih stag: update traefik domains
  services/traefik/config/aws_dyn_cfg.yml
Labels: t:bug, FAST

#601 Remove harcoded docker networks
  scripts/common.Makefile
Labels: p:mid-prio, FAST

#602 Make interactive services network external
  services/simcore/docker-compose.yml
Labels: FAST

#604 Fix external networks
  services/admin-panels/template.env
  services/adminer/template.env
  services/appmotion_gateway/template.api_env
  services/filestash/template.env
  services/graylog/template.env
  services/jaeger/template.env
  services/monitoring/template.env
  services/portainer/template.env
  services/redis-commander/template.env
  services/registry/template.env
  services/traefik/template.env
Labels: t:bug

#607 606 aiohttp simcore monitoring
  services/monitoring/grafana/provisioning/allDeployments/dashboards/simcore/AiohttpServices.json
  services/monitoring/grafana/provisioning/allDeployments/dashboards/simcore/SimcoreServices.json
Labels: observability

#610 Fix: Use `docker stack config`
  scripts/docker-compose-config.bash
  services/simcore/docker-compose.yml
Labels: t:bug, p:high-prio

#612 add services into the monitored network
  services/simcore/docker-compose.yml
Labels: FAST

#617 Move traefik dynamic config to ./osparc-config
  .gitignore
  scripts/common.Makefile
  services/traefik/.gitignore
  services/traefik/Makefile
  services/traefik/config/aws_dyn_cfg.yml
  services/traefik/config/dalco_dyn_cfg.yml
  services/traefik/config/local_dyn_cfg.yml
  services/traefik/config/master_dyn_cfg.yml
  services/traefik/config/public_dyn_cfg.yml
  services/traefik/docker-compose.aws.yml
  services/traefik/docker-compose.dalco.yml
  services/traefik/docker-compose.local.yml
  services/traefik/docker-compose.master.yml
  services/traefik/docker-compose.public.yml
  services/traefik/docker-compose.yml.j2
Labels: p:mid-prio, SECURITY

#624 Add pylint pre-commit hook
  .pre-commit-config.yaml
  .pylintrc
  scripts/dockerNodeStats/main.py
  scripts/handleEnvVars/main.py
  scripts/handleEnvVars/requirements.txt
  scripts/helpers/gen_pwd.py
  scripts/helpers/get_unused_aws_key_pairs.py
  scripts/pre-commit-hooks/runPylint/launch.bash
  scripts/pre-commit-hooks/runPylint/requirements.txt
  scripts/pre-commit-hooks/validateTemplateDotEnv/.env.main.py
  scripts/pre-commit-hooks/validateTemplateDotEnv/template.env.main.py
  scripts/provisionDatabase/provision_database.py
  scripts/s3BucketOptions/set_bucket_cors.py
  scripts/s3BucketOptions/set_bucket_lifecycle_policy.py
  scripts/s3BucketOptions/set_bucket_lifecycle_policy_ceph.py
  scripts/s3RobustCopy/main.py
  services/filestash/create_config.py
  services/graylog/scripts/configure.py
  services/monitoring/grafana/scripts/export.py
  services/monitoring/grafana/scripts/import.py
  services/simcore/envsubst_escape_dollar_sign.py
Labels: p:low-prio
