Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2024-05, with the labels that each got.

#674 Remove internal monitoring network
  services/monitoring/docker-compose.yml.j2
Labels: p:high-prio

#681 Fix makefile issues
  scripts/common.Makefile
  scripts/portable.sh
  services/monitoring/grafana/scripts/export.py
Labels: t:bug, p:high-prio, FAST

#682 Prometheus: use private dns to scrape external clusters
  services/monitoring/prometheus/prometheus-aws.yml
Labels: FAST

#683 [AWS]: use EC2 private IP instead of private DNS name as it does not resolve inside the containers
  services/monitoring/prometheus/prometheus-aws.yml
Labels: FAST
