Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2024-11, with the labels that each got.

#846 [v1.78.0] PROD inhouse tip: fix simcore traefik postgres route
  services/simcore/docker-compose.deploy.public.yml
Labels: t:bug

#864 💄 Add: Make RUT replica configurable via envvar
  services/simcore/docker-compose.deploy.aws.yml
  services/simcore/docker-compose.deploy.dalco.yml
  services/simcore/docker-compose.deploy.public.yml
  services/simcore/docker-compose.yml
Labels: t:enhancement, FAST

#886 vendors stack: support multiple domains & maintenance mode
  scripts/common.Makefile
  services/maintenance-page/docker-compose.yml.j2
  services/maintenance-page/template.env
  services/vendors/.gitignore
  services/vendors/Makefile
  services/vendors/docker-compose.yml.j2
  services/vendors/j2cli_customization.py
  services/vendors/template.env
Labels: p:high-prio

#889 Polish registry s3 endpoint env
  services/registry/template.env
Labels: p:low-prio, FAST

#891 Update new service intro section in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: p:low-prio
