Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2024-09, with the labels that each got.

#784 Fix Migration Traefik v2.10-->v2.11: IPWhitelist middleware is now ipallowlist
  services/simcore/docker-compose.yml
  services/traefik/docker-compose.letsencrypt.dns.yml.j2
  services/traefik/docker-compose.yml.j2
Labels: t:bug

#785 Fix traefik global http --> https redirect
  services/traefik/docker-compose.aws.yml
  services/traefik/docker-compose.dalco.yml
  services/traefik/docker-compose.master.yml
  services/traefik/docker-compose.public.yml
  services/traefik/docker-compose.yml.j2
Labels: t:bug, p:high-prio

#786 OPS Traefik: disable traefik v2 core syntax
  services/traefik/docker-compose.aws.yml
  services/traefik/docker-compose.dalco.yml
  services/traefik/docker-compose.letsencrypt.http.yml
  services/traefik/docker-compose.local.yml
  services/traefik/docker-compose.master.yml
  services/traefik/docker-compose.public.yml
  services/traefik/docker-compose.yml.j2
Labels: t:bug, p:high-prio

#780 Add simcore RUT helm chart
  .gitignore
  charts/Makefile
  charts/adminer/values.yaml.gotmpl
  charts/simcore-charts/.gitignore
  charts/simcore-charts/common-helpers/.helmignore
  charts/simcore-charts/common-helpers/Chart.yaml
  charts/simcore-charts/common-helpers/templates/_helpers.tpl
  charts/simcore-charts/resource-usage-tracker/.helmignore
  charts/simcore-charts/resource-usage-tracker/Chart.lock
  charts/simcore-charts/resource-usage-tracker/Chart.yaml
  charts/simcore-charts/resource-usage-tracker/templates/NOTES.txt
  charts/simcore-charts/resource-usage-tracker/templates/_helpers.tpl
  charts/simcore-charts/resource-usage-tracker/templates/deployment.yaml
  charts/simcore-charts/resource-usage-tracker/templates/hpa.yaml
  charts/simcore-charts/resource-usage-tracker/templates/ingress.yaml
  charts/simcore-charts/resource-usage-tracker/templates/secret.yaml
  charts/simcore-charts/resource-usage-tracker/templates/service.yaml
  charts/simcore-charts/resource-usage-tracker/templates/serviceaccount.yaml
  charts/simcore-charts/resource-usage-tracker/templates/tests/test-connection.yaml
  charts/simcore-charts/resource-usage-tracker/values.yaml.gotmpl
  charts/traefik/values.common.yaml.gotmpl
  charts/traefik/values.insecure.yaml.gotmpl
  charts/traefik/values.secure.yaml.gotmpl
  charts/traefik/values.webinternal.yaml.gotmpl
  services/.gitignore
  services/simcore/docker-compose.deploy.aws.yml
  services/traefik/docker-compose.aws.yml
Labels: p:mid-prio

#787 Use env to set kubernetes webinternal port
  charts/traefik/values.webinternal.yaml.gotmpl
Labels: t:enhancement, FAST

#789 Cleanup docker node labels
  services/adminer/docker-compose.aws.yml
  services/adminer/docker-compose.dalco.yml
  services/adminer/docker-compose.master.yml
  services/appmotion_gateway/docker-compose.aws.yml
Labels: t:enhancement, FAST

#793 Kubernetes RUT: pull image always
  charts/simcore-charts/resource-usage-tracker/values.yaml.gotmpl
Labels: t:bug

#794 Clearer comments for grafana script makefile targets
  services/monitoring/Makefile
Labels: observability, FAST

#795 Bump Python version 3.11
  .python-version
Labels: p:mid-prio, FAST, SECURITY

#796 Bump portainer_portainer memory limit to 1G
  services/portainer/docker-compose.yml
Labels: t:bug, p:high-prio

#803 Redis commander: use connections file
  services/redis-commander/.gitignore
  services/redis-commander/Makefile
  services/redis-commander/config.json.j2
  services/redis-commander/docker-compose.aws.yml
  services/redis-commander/docker-compose.dalco.yml
  services/redis-commander/docker-compose.public.yml
  services/redis-commander/docker-compose.yml
  services/redis-commander/template.env
Labels: t:enhancement, p:mid-prio

#809 redis commander: handle none redis_user
  services/redis-commander/config.json.j2
Labels: t:enhancement

#811 Kubernets RUT: update Redis env
  charts/simcore-charts/resource-usage-tracker/values.yaml.gotmpl
Labels: t:bug

#815 increase scrape rate on simcore stuff
  services/monitoring/prometheus/prometheus-base.yml
  services/monitoring/prometheus/prometheus-simcore.yml
Labels: FAST

#817 redis commander: use staging env for staging connections
  services/redis-commander/config.json.j2
  services/redis-commander/template.env
Labels: t:bug

#823 jaeger: use ops node label constraint
  services/jaeger/Makefile
  services/jaeger/docker-compose.aws.yml
  services/jaeger/docker-compose.dalco.yml
  services/jaeger/docker-compose.master.yml
  services/jaeger/docker-compose.yml
Labels: t:enhancement, p:mid-prio
