Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2024-08, with the labels that each got.

#726 Registry ptc use port host mode
  services/registry/docker-compose.yml
  services/registry/template.env
Labels: p:mid-prio

#729 Replicate static-webserver
  services/simcore/docker-compose.yml
Labels: p:mid-prio

#731 Use traefik v3
  services/admin-panels/docker-compose.yml.j2
  services/appmotion_gateway/docker-compose.yml
  services/minio/docker-compose.yaml.j2
  services/monitoring/docker-compose.yml.j2
  services/traefik/docker-compose.yml.j2
Labels: t:enhancement, t:infra-ops, refactoring

#732 Remove old CI-Dockerimage related files
  ci/ciRunsDockerContainer/Dockerfile
  ci/ciRunsDockerContainer/Makefile
  ci/ciRunsDockerContainer/README.md
  ci/ciRunsDockerContainer/docker-compose-deploy.yml
  ci/ciRunsDockerContainer/dockerhub_login.bash
  ci/ciRunsDockerContainer/mozillateam.pref
  ci/ciRunsDockerContainer/template.env
Labels: p:low-prio, FAST, refactoring

#733 k8s cert manager: self signed certs post install annotions
  charts/cert-manager/values.selfsigned.yaml.gotmpl
Labels: p:mid-prio

#735 Remove k8s base64 secret envs
  charts/cert-manager/values.route53.yaml.gotmpl
Labels: p:mid-prio

#739 🐛 Fix: Issues from traefikV3 update
  services/adminer/docker-compose.yml
  services/filestash/docker-compose.yml
  services/traefik/docker-compose.aws.yml
  services/traefik/docker-compose.dalco.yml
  services/traefik/docker-compose.letsencrypt.http.yml
  services/traefik/docker-compose.local.yml
  services/traefik/docker-compose.master.yml
  services/traefik/docker-compose.public.yml
  services/traefik/docker-compose.yml.j2
Labels: t:bug, p:high-prio, t:infra-ops, FAST

#740 Remove traefik labels from registry pull through cache
  services/registry/docker-compose.yml
Labels: t:bug

#742 Revert traefik v3
  services/admin-panels/docker-compose.yml.j2
  services/appmotion_gateway/docker-compose.yml
  services/graylog/docker-compose.yml
  services/jaeger/docker-compose.yml
  services/minio/docker-compose.yaml.j2
  services/monitoring/docker-compose.yml.j2
  services/portainer/docker-compose.yml
  services/redis-commander/docker-compose.yml
  services/registry/docker-compose.yml
  services/simcore/docker-compose.deploy.aws.yml
  services/simcore/docker-compose.deploy.dalco.yml
  services/simcore/docker-compose.deploy.local.yml
  services/simcore/docker-compose.deploy.master.yml
  services/simcore/docker-compose.yml
  services/traefik/docker-compose.aws.yml
  services/traefik/docker-compose.dalco.yml
  services/traefik/docker-compose.letsencrypt.http.yml
  services/traefik/docker-compose.local.yml
  services/traefik/docker-compose.master.yml
  services/traefik/docker-compose.public.yml
  services/traefik/docker-compose.yml.j2
Labels: p:high-prio, FAST

#760 Make pylint pass
  scripts/purge-docker-registry/docker-registry-curl.bash
  scripts/s3RobustCopy/main.py
  services/graylog/scripts/configure.py
  services/monitoring/grafana/scripts/export.py
  services/monitoring/grafana/scripts/import.py
Labels: t:enhancement, p:low-prio, FAST

#764 Redis password dalco
  services/redis-commander/docker-compose.dalco.yml
Labels: t:bug, p:high-prio

#770 Fix dalco staging redis pwd
  services/redis-commander/docker-compose.dalco.yml
  services/redis-commander/template.env
Labels: p:high-prio

#775 Fix: Bugs introduced in dependency upgrade
  services/monitoring/docker-compose.yml.j2
  services/monitoring/grafana/scripts/import.py
Labels: t:enhancement, t:infra-ops, FAST

#743 ⬆️ Upgrade to traefik v3 (2nd trial)
  services/admin-panels/docker-compose.yml.j2
  services/appmotion_gateway/docker-compose.yml
  services/graylog/docker-compose.yml
  services/jaeger/docker-compose.yml
  services/minio/docker-compose.yaml.j2
  services/monitoring/docker-compose.yml.j2
  services/portainer/docker-compose.yml
  services/redis-commander/docker-compose.yml
  services/registry/docker-compose.yml.j2
  services/simcore/docker-compose.deploy.aws.yml
  services/simcore/docker-compose.deploy.dalco.yml
  services/simcore/docker-compose.deploy.local.yml
  services/simcore/docker-compose.deploy.master.yml
  services/simcore/docker-compose.yml
  services/traefik/docker-compose.aws.yml
  services/traefik/docker-compose.dalco.yml
  services/traefik/docker-compose.letsencrypt.http.yml
  services/traefik/docker-compose.local.yml
  services/traefik/docker-compose.master.yml
  services/traefik/docker-compose.public.yml
  services/traefik/docker-compose.yml.j2
Labels: t:enhancement
