Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2024-04, with the labels that each got.

#626 Move grafana dashboards
  .gitignore
  scripts/common.Makefile
  services/monitoring/Makefile
  services/monitoring/grafana/.gitignore
  services/monitoring/grafana/provisioning/.gitignore
  services/monitoring/grafana/provisioning/allDeployments/alerts/osparc_alerts.json
  services/monitoring/grafana/provisioning/allDeployments/dashboards/nih-metrics/SPARC DRC Metrics.json
  services/monitoring/grafana/provisioning/allDeployments/dashboards/ops/Cardinality Explorer.json
  services/monitoring/grafana/provisioning/allDeployments/dashboards/ops/GPU Nodes.json
  services/monitoring/grafana/provisioning/allDeployments/dashboards/ops/SmokePing.json
  services/monitoring/grafana/provisioning/allDeployments/dashboards/ops/Traefik2.json
  services/monitoring/grafana/provisioning/allDeployments/dashboards/simcore/AiohttpServices.json
  services/monitoring/grafana/provisioning/allDeployments/dashboards/simcore/Metrics.json
  services/monitoring/grafana/provisioning/allDeployments/dashboards/simcore/PostgreSQL Database.json
  services/monitoring/grafana/provisioning/allDeployments/dashboards/simcore/RabbitMQ-Overview.json
  services/monitoring/grafana/provisioning/allDeployments/dashboards/simcore/SimcoreServices.json
  services/monitoring/grafana/provisioning/allDeployments/dashboards/system/Docker Swarm Overview.json
  services/monitoring/grafana/provisioning/allDeployments/dashboards/system/Nodes -  Detailed Insights.json
  services/monitoring/grafana/provisioning/allDeployments/dashboards/system/Nodes - Overview.json
  services/monitoring/grafana/provisioning/allDeployments/datasources/1.json
  services/monitoring/grafana/provisioning/allDeployments/datasources/2.json
  services/monitoring/grafana/provisioning/osparc-master-zmt.click/datasources2dashboards.yaml
  services/monitoring/grafana/provisioning/osparc-master.speag.com/dashboards/ops/Ceph  - Cluster.json
  services/monitoring/grafana/provisioning/osparc-master.speag.com/datasources2dashboards.yaml
  services/monitoring/grafana/provisioning/osparc-staging.io/dashboards/simcore/s4l-lite-admin-overview.json
  services/monitoring/grafana/provisioning/osparc-staging.io/datasources2dashboards.yaml
  services/monitoring/grafana/provisioning/osparc-testing.click/datasources2dashboards.yaml
  services/monitoring/grafana/provisioning/osparc.io/dashboards/simcore/s4l-lite-admin-overview.json
  services/monitoring/grafana/provisioning/osparc.io/datasources2dashboards.yaml
  services/monitoring/grafana/provisioning/osparc.local/datasources2dashboards.yaml
  services/monitoring/grafana/provisioning/osparc.speag.com/dashboards/ops/Ceph  - Cluster.json
  services/monitoring/grafana/provisioning/osparc.speag.com/dashboards/ops/MinIO Dashboard.json
  services/monitoring/grafana/provisioning/osparc.speag.com/dashboards/simcore/Metrics Staging.json
  services/monitoring/grafana/provisioning/osparc.speag.com/datasources2dashboards.yaml
  services/monitoring/grafana/provisioning/sim4life.io/dashboards/simcore/s4l_admin_overview.json
  services/monitoring/grafana/provisioning/sim4life.io/datasources2dashboards.yaml
  services/monitoring/grafana/provisioning/tip.itis.swiss/dashboards/simcore/admin-overview.json
  services/monitoring/grafana/provisioning/tip.itis.swiss/datasources2dashboards.yaml
  services/monitoring/grafana/scripts/import.py
Labels: p:mid-prio

#627 Fix validations script
  scripts/deployments/validate_simcore_stack_yml.bash
Labels: t:infra-ops, refactoring

#628 Fix validation script - 2
  scripts/deployments/validate_simcore_stack_yml.bash
Labels: e2e & test

#629 adding basic authentication to external clusters
  services/monitoring/prometheus/prometheus-aws.yml
Labels: t:enhancement, FAST

#630 used wrong password entry
  services/monitoring/prometheus/prometheus-aws.yml
Labels: FAST

#633 Director v2 avoid ops node
  services/simcore/docker-compose.yml
Labels: p:low-prio, FAST

#644 Some refactoring
  services/monitoring/Makefile
  services/monitoring/grafana/.gitignore
  services/monitoring/grafana/scripts/export.py
  services/monitoring/prometheus/prometheus-federation.yml
Labels: observability

#613 ♻️Change: Switch to `docker stack config`
  .pre-commit-config.yaml
  Makefile
  scripts/deployments/README.MD
  scripts/deployments/compose_stack_yml.bash
  scripts/deployments/deploy_everything_locally.sh
  scripts/deployments/prepare_simcore_stack.bash
  scripts/deployments/start_simcore_locally.bash
  scripts/docker-compose-config.bash
  scripts/docker-stack-config.bash
  scripts/pre-commit-hooks/stack-yml-generated-is-valid/launch.bash
  scripts/pre-commit-hooks/validateDockerComposeNoDuplication/launch.bash
  services/admin-panels/Makefile
  services/adminer/Makefile
  services/appmotion_gateway/Makefile
  services/filestash/Makefile
  services/graylog/Makefile
  services/jaeger/Makefile
  services/mail/Makefile
  services/maintenance-page/Makefile
  services/minio/Makefile
  services/monitoring/Makefile
  services/pg-backup/Makefile
  services/portainer/Makefile
  services/redis-commander/Makefile
  services/registry/Makefile
  services/simcore/docker-compose.yml
  services/traefik/Makefile
Labels: t:enhancement, p:mid-prio

#646 ⚡️ Reduce number of git-repo interconnections (`3 --> 1`)
  .gitignore
  scripts/common.Makefile
  services/monitoring/Makefile
Labels: t:enhancement, observability, t:infra-ops

#650 registry: remove hardcoded aws region
  services/registry/docker-compose.yml
  services/registry/template.env
Labels: t:bug, p:high-prio, FAST

#652 Update filestash configuration
  services/filestash/create_config.py
Labels: t:enhancement, FAST

#657 Increase webserver and storage replicas on master for testing
  services/simcore/docker-compose.deploy.master.yml
Labels: e2e & test
