Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2024-10, with the labels that each got.

#835 OTEL: add log level configuration via env
  services/jaeger/docker-compose.yml
  services/jaeger/opentelemetry-collector-config.yaml
  services/jaeger/template.env
Labels: p:high-prio

#838 Graylog 6.0: update configuration script
  services/graylog/scripts/configure.py
  services/graylog/template.env
Labels: p:mid-prio

#840 registries: Add log level env
  services/registry/docker-compose.yml.j2
  services/registry/template.env
Labels: FAST

#836 ♻️ k8s: Introduce Namespaces + Cleanups
  charts/Makefile
  charts/README.md
  charts/adminer/values.yaml.gotmpl
  charts/cert-manager/values.selfsigned.yaml.gotmpl
  charts/traefik/values.insecure.yaml.gotmpl
  charts/traefik/values.secure.yaml.gotmpl
  charts/traefik/values.webinternal.yaml.gotmpl
Labels: t:enhancement

#839 Fix: opentelemetry errors in EFS guardian
  services/simcore/docker-compose.yml
Labels: t:bug, observability, FAST

#843 jaeger: increase ram
  services/jaeger/docker-compose.yml
Labels: FAST

#849 Raise simcore agent memory limit
  services/simcore/docker-compose.yml
Labels: p:high-prio

#848 Add k8s portainer
  charts/adminer/values.yaml.gotmpl
  charts/portainer/values.yaml.gotmpl
  charts/traefik/values.insecure.yaml.gotmpl
  charts/traefik/values.secure.yaml.gotmpl
Labels: t:infra-ops

#850 Add vendor stack
  .github/PULL_REQUEST_TEMPLATE.md
  services/traefik/docker-compose.yml.j2
  services/traefik/template.env
  services/vendors/Makefile
  services/vendors/docker-compose.yml
  services/vendors/template.env
Labels: p:high-prio

#854 ✨ Add: k8s S3 CSI to be used with portainer
  .gitignore
  charts/csi-s3/values.yaml.gotmpl
  charts/portainer/values.yaml.gotmpl
Labels: t:bug, p:high-prio

#858 Remove `stack-yaml-generated-is-valid` pre-commit hook
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  scripts/pre-commit-hooks/stack-yml-generated-is-valid/.gitignore
  scripts/pre-commit-hooks/stack-yml-generated-is-valid/launch.bash
  scripts/pre-commit-hooks/stack-yml-generated-is-valid/requirements.txt
Labels: p:low-prio
