Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2024-07, with the labels that each got.

#719 Add REDIS_PASSWORD for redis-commander
  services/redis-commander/docker-compose.yml
  services/redis-commander/template.env
Labels: FAST

#722 🐛 Add password auth to redis-prometheus-exporter
  services/monitoring/docker-compose.yml.j2
  services/monitoring/template.env
Labels: t:bug

#724 Make appmotion db host configurable
  services/appmotion_gateway/template.api_env
  services/appmotion_gateway/template.env
Labels: p:mid-prio

#725 Introduce pull through cache registry
  services/registry/docker-compose.yml
  services/registry/template.env
Labels: p:high-prio, t:infra-ops
