Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2024-02, with the labels that each got.

#545 Update zmt master certs cfg
  services/traefik/config/aws_dyn_cfg.yml
Labels: t:bug

#548 Rename dynamic scheduler
  services/monitoring/grafana/provisioning/allDeployments/dashboards/simcore/SimcoreService.json
  services/monitoring/prometheus/prometheus-simcore.yml
  services/simcore/docker-compose.yml
Labels: p:high-prio, FAST

#557 Fix appmotion certs
  services/traefik/config/aws_dyn_cfg.yml
  services/traefik/config/dalco_dyn_cfg.yml
  services/traefik/config/master_dyn_cfg.yml
  services/traefik/config/public_dyn_cfg.yml
Labels: t:bug, FAST

#565 Fix prometheus reservations
  services/monitoring/docker-compose.aws.yml
  services/monitoring/docker-compose.yml.j2
Labels: p:mid-prio, FAST

#558 Fix 299 pr
  services/traefik/config/aws_dyn_cfg.yml
Labels: t:bug, FAST

#575 Clean up master deployments traefik domains
  services/traefik/config/aws_dyn_cfg.yml
  services/traefik/config/master_dyn_cfg.yml
Labels: p:mid-prio

#576 Clean up staging traefik certs
  services/traefik/config/aws_dyn_cfg.yml
Labels: p:mid-prio, FAST

#577 Fix storage traefik docker network
  services/simcore/docker-compose.yml
Labels: p:low-prio, FAST

#580 Fix garbage collection hostname
  services/simcore/docker-compose.yml
Labels: t:bug

#583 Changes: osparc-config MR433 - introduce assets folder
  scripts/ciOffsiteBackup/emailUsersUponProjectOffsiteBackup/main.py
  scripts/ciOffsiteBackup/emailUsersUponProjectOffsiteBackup/requirements.txt
  scripts/remove_connections_delete_db.SQL
  services/maintenance-page/docker-compose.yml.j2
Labels: FAST, refactoring

#586 parse service name
  scripts/deployments/validate_simcore_stack_yml.bash
Labels: t:bug

#587 added prefix simcore-service in front
  scripts/deployments/validate_simcore_stack_yml.bash
Labels: t:bug

#588 Revert to use "simcore-service" as binary, as migration service is anyway skipped.
  scripts/deployments/validate_simcore_stack_yml.bash
Labels: t:bug

#589 Avoid autoscaled nodes
  services/admin-panels/Makefile
  services/admin-panels/docker-compose.dalco.yml
  services/admin-panels/docker-compose.master.yml
  services/admin-panels/docker-compose.yml.j2
  services/maintenance-page/docker-compose.yml.j2
  services/monitoring/docker-compose.yml.j2
  services/portainer/docker-compose.yml
  services/traefik/docker-compose.yml.j2
Labels: p:mid-prio, FAST

#591 Clean up prod traefik certs
  services/traefik/config/aws_dyn_cfg.yml
  services/traefik/config/dalco_dyn_cfg.yml
  services/traefik/config/public_dyn_cfg.yml
Labels: t:enhancement, p:mid-prio, FAST
