Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2024-12, with the labels that each got.

#899 Expose dynamic scheduler UI
  services/simcore/docker-compose.yml
Labels: p:mid-prio, FAST

#893 🐛 Fix: Traefik www redirect
  services/admin-panels/jupyter_server_config.py.template
  services/traefik/docker-compose.letsencrypt.dns.yml.j2
  services/traefik/docker-compose.yml.j2
Labels: t:bug

#904 Fix: J2 issue in gitlab CI/CD
  scripts/common.Makefile
Labels: t:bug

#905 Fix: J2 issue in gitlab CI/CD - Attempt2
  Makefile
Labels: t:bug

#906 Fix: J2 issue in gitlab CI/CD - Attempt3
  Makefile
  scripts/common.Makefile
Labels: t:bug

#908 Fix: traefik `www` redirect properly
  scripts/common.Makefile
  services/traefik/docker-compose.yml.j2
  services/traefik/template.env
Labels: t:bug, p:mid-prio

#916 AWS Kubernetes: prod volume management
  charts/aws-ebs-csi-driver/values.yaml.gotmpl
  charts/portainer/values.ebs-pv.yaml.gotmpl
  charts/portainer/values.s3-pv.yaml.gotmpl
  charts/portainer/values.yaml.gotmpl
Labels: t:enhancement, p:mid-prio
