Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2025-04, with the labels that each got.

#1004 Fix Graylog error message OEC content pack configuration
  services/graylog/data/contentpacks/osparc-custom-content-pack-v2.json
Labels: t:bug, p:high-prio

#1005 2025/add/graylog alerts
  scripts/common.Makefile
  services/graylog/data/contentpacks/osparc-custom-content-pack-v2.json
  services/graylog/scripts/alerts.template.yaml
  services/graylog/scripts/configure.py
  services/graylog/template.env
Labels: observability, p:mid-prio, refactoring

#996 Upgrade ops dependencies to support arm
  services/admin-panels/docker-compose.yml.j2
  services/monitoring/docker-compose.yml.j2
Labels: t:enhancement, t:infra-ops

#1009 Fix graylog content pack
  services/graylog/data/contentpacks/osparc-custom-content-pack-v2.json
Labels: t:bug, observability, p:high-prio, FAST

#910 ✨ Add: Grafana tempo
  .gitignore
  Makefile
  services/jaeger/opentelemetry-collector-config.yaml
  services/monitoring/Makefile
  services/monitoring/docker-compose.yml.j2
  services/monitoring/grafana/terraform/datasources.tf
  services/monitoring/grafana/terraform/main.tf.j2
  services/monitoring/grafana/terraform/variables.tf
  services/monitoring/template.env
  services/monitoring/tempo_config.yaml.j2
Labels: t:enhancement, observability, EPIC

#1010 Redis commander: rolling config updates
  services/redis-commander/.gitignore
  services/redis-commander/Makefile
  services/redis-commander/docker-compose.yml.j2
  services/redis-commander/template.env
Labels: t:enhancement

#1017 prepare simcore stack: keep secret path processing
  scripts/deployments/prepare_simcore_stack.bash
Labels: t:bug

#1021 Filestash: add config dep to docker compose target
  services/filestash/Makefile
Labels: t:bug

#1023 Add sto-worker-cpu-bound service
  services/simcore/docker-compose.yml.j2
Labels: FAST

#1024 Add update portainer password help comment
  services/portainer/Makefile
Labels: FAST

#1029 Fix traefik www capture router
  services/traefik/docker-compose.yml.j2
Labels: t:bug, p:high-prio

#1035 Expose dynamic scheduler API
  services/simcore/docker-compose.yml.j2
Labels: FAST

#969 Add `docker-api-proxy` service
  services/simcore/docker-compose.yml.j2
Labels: SECURITY
