Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2025-05, with the labels that each got.

#979 [Kubernetes] Introduce on-prem persistent Storage (Longhorn) :tada:
  charts/Makefile
  charts/longhorn/README.md
  charts/longhorn/values.yaml.gotmpl
  charts/portainer/values.longhorn-pv.yaml.gotmpl
  charts/traefik/values.insecure.yaml.gotmpl
  charts/traefik/values.secure.yaml.gotmpl
Labels: t:enhancement

#1042 Upgrade Dependencies: Prom, Graylog, Grafana, Traefik, etc
  services/graylog/docker-compose.yml.j2
  services/jaeger/docker-compose.yml.j2
  services/monitoring/docker-compose.yml.j2
  services/portainer/docker-compose.yml
  services/traefik/docker-compose.yml.j2
Labels: t:enhancement, t:dependencies

#1046 traefik v3.4 deprecated `traefik.docker.` in favor of `traefik.swarm.` labels
  services/admin-panels/docker-compose.yml.j2
  services/appmotion_gateway/docker-compose.yml.j2
  services/filestash/docker-compose.yml.j2
  services/graylog/docker-compose.yml.j2
  services/jaeger/docker-compose.yml.j2
  services/maintenance-page/docker-compose.yml.j2
  services/minio/docker-compose.yaml
  services/monitoring/docker-compose.yml.j2
  services/redis-commander/docker-compose.yml.j2
  services/registry/docker-compose.yml.j2
  services/simcore/docker-compose.yml.j2
  services/traefik/docker-compose.yml.j2
  services/vendors/docker-compose.yml.j2
Labels: FAST

#1053 Update RUT helmchart values
  charts/simcore-charts/resource-usage-tracker/values.yaml.gotmpl
Labels: FAST

#1055 Simcore helm charts: use external db envs
  charts/simcore-charts/resource-usage-tracker/values.yaml.gotmpl
Labels: FAST

#1065 Fix director metrics port
  services/monitoring/prometheus/prometheus-simcore.yml
Labels: t:bug, FAST
