Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2025-07, with the labels that each got.

#1109 inhouse tip prometheus: scrape simcore services
  services/monitoring/Makefile
Labels: t:bug, observability, FAST

#1110 Kubernetes logging: storage configuration
  charts/victoria-logs/values.ebs-storage.yaml.gotmpl
  charts/victoria-logs/values.topolvm-storage.yaml.gotmpl
  charts/victoria-logs/values.yaml.gotmpl
Labels: FAST

#1125 Add portainer registry configuration 🚨
  scripts/.gitignore
  scripts/common.Makefile
  services/monitoring/grafana/Makefile
  services/portainer/Makefile
  services/portainer/docker-compose.letsencrypt.dns.yml
  services/portainer/docker-compose.letsencrypt.http.yml
  services/portainer/scripts/configure_portainer_registry.py
  services/portainer/scripts/requirements.txt
Labels: t:enhancement

#1136 Document metabase optional configuration (email, ...)
  services/metabase/README.md
Labels: t:enhancement

#1139 Kubernetes simcore: add pod security standard
  charts/SECURITY.md
  charts/simcore-charts/common-helpers/Chart.yaml
  charts/simcore-charts/common-helpers/templates/_helpers.tpl
  charts/simcore-charts/namespace.yaml
  charts/simcore-charts/resource-usage-tracker/Chart.yaml
  charts/simcore-charts/resource-usage-tracker/templates/deployment.yaml
  charts/simcore-charts/resource-usage-tracker/values.yaml.gotmpl
Labels: SECURITY

#1141 Kubernetes topolvm: fix pv removal doc
  charts/topolvm/README.md
Labels: FAST

#1142 Update k8s resource usage tracker chart lock
  .pre-commit-config.yaml
  charts/simcore-charts/resource-usage-tracker/Chart.lock
Labels: t:bug, FAST

#1130 Fix: tempo remote writer reciever issue
  services/monitoring/docker-compose.yml.j2
Labels: observability, FAST

#1144 Metabase db cleanup script
  services/metabase/.gitignore
  services/metabase/Makefile
  services/metabase/README.md
  services/metabase/remove_metabase.sql.template
Labels: t:enhancement, t:infra-ops, FAST

#1118 Refactor: ops-traefik configuration (2nd attempt)
  scripts/common.Makefile
  services/graylog/docker-compose.local.yml
  services/graylog/docker-compose.yml.j2
  services/maintenance-page/docker-compose.yml.j2
  services/portainer/Makefile
  services/portainer/scripts/configure_portainer_registry.py
  services/portainer/template.env
  services/traefik/Makefile
  services/traefik/docker-compose.aws.yml
  services/traefik/docker-compose.dalco.yml
  services/traefik/docker-compose.local.yml
  services/traefik/docker-compose.master.yml
  services/traefik/docker-compose.public.yml
  services/traefik/docker-compose.yml.j2
  services/traefik/template.env
Labels: observability, refactoring

#1041 Instrument Traefik - Connect traefiks to opentelemetry
  services/simcore/docker-compose.deploy.aws.yml
  services/simcore/docker-compose.deploy.dalco.yml
  services/simcore/docker-compose.deploy.local.yml
  services/simcore/docker-compose.deploy.master.yml
  services/simcore/docker-compose.deploy.public.yml
Labels: observability

#1152 Kubernetes: update local configuration
  charts/Makefile
Labels: t:bug, FAST

#1143 Add: Chatbox vendor service
  scripts/deployments/deploy_everything_locally.bash
  services/maintenance-page/docker-compose.yml.j2
  services/vendors/docker-compose.yml.j2
  services/vendors/j2cli_customization.py
  services/vendors/template.env
Labels: p:high-prio

#1155 Monitoring: add `wb-auth` scraping
  services/monitoring/prometheus/prometheus-simcore.yml
Labels: t:bug, FAST
