Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2025-09, with the labels that each got.

#1195 Add api-worker simcore service
  services/simcore/docker-compose.yml.j2
Labels: FAST

#1200 Fix prometheus high cardinality due to tempo `span_name`
  services/monitoring/tempo_config.yaml.j2
Labels: observability, FAST

#1179 Add (ha) rabbit cluster (but not use it) :warning:
  services/rabbit/.gitignore
  services/rabbit/.operations.Makefile
  services/rabbit/Makefile
  services/rabbit/README.md
  services/rabbit/configs/erlang.cookie.secret.template
  services/rabbit/configs/haproxy.cfg.j2
  services/rabbit/configs/rabbitmq.conf.j2
  services/rabbit/docker-compose.loadbalancer.yml.j2
  services/rabbit/docker-compose.node0x.yml.j2
  services/rabbit/template.env
Labels: blocked / paused

#1150 Refactor: pg-backup (remove dedicated service)
  services/pg-backup/Makefile
  services/pg-backup/README.md
  services/pg-backup/docker-compose.yml
  services/pg-backup/template.env
Labels: observability, t:infra-ops, e2e & test, refactoring

#1221 Enable Chatbot for S4L products
  services/vendors/docker-compose.yml.j2
  services/vendors/template.env
Labels: t:bug
