Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2025-08, with the labels that each got.

#1169 Kubernetes: global deny network policy for simcore
  charts/adminer/templates/networkpolicy.yaml
  charts/calico-configuration/README.md
  charts/calico-configuration/templates/globalpolicy.yaml
  charts/simcore-charts/resource-usage-tracker/templates/deployment.yaml
  charts/simcore-charts/resource-usage-tracker/templates/networkpolicy.yaml
  charts/simcore-charts/resource-usage-tracker/values.yaml.gotmpl
Labels: SECURITY

#1172 Fix validate simcore settings script
  scripts/deployments/validate_simcore_stack_yml.bash
Labels: t:bug, FAST

#1174 Simcore: remove rollback update policy
  services/simcore/docker-compose.yml.j2
Labels: t:bug, FAST

#1177 Use shorter names for traefik placeholder
  services/simcore/docker-compose.yml.j2
Labels: t:bug, FAST

#1178 Fix validate simcore
  scripts/deployments/validate_simcore_stack_yml.bash
Labels: t:bug, FAST

#1058 Introduce Logging Stack: Add fluentd, add loki (🚧🚧 DEVOPS 🚧🚧)
  scripts/deployments/deploy_everything_locally.bash
  services/graylog/GraylogWorkflow.png
  services/graylog/docker-compose.aws.yml
  services/graylog/docker-compose.dalco.yml
  services/graylog/docker-compose.master.yml
  services/logging/.gitignore
  services/logging/Makefile
  services/logging/README.md
  services/logging/data/contentpacks/osparc-custom-content-pack-v2.json
  services/logging/docker-compose.aws.yml
  services/logging/docker-compose.dalco.yml
  services/logging/docker-compose.letsencrypt.dns.yml
  services/logging/docker-compose.letsencrypt.http.yml
  services/logging/docker-compose.local.yml
  services/logging/docker-compose.master.yml
  services/logging/docker-compose.yml.j2
  services/logging/fluentd/Dockerfile
  services/logging/fluentd/Makefile
  services/logging/fluentd/README.md
  services/logging/fluentd/fluent.conf
  services/logging/loki.yaml
  services/logging/scripts/.gitignore
  services/logging/scripts/README.md
  services/logging/scripts/alerts.template.yaml
  services/logging/scripts/configure.py
  services/logging/scripts/requirements.txt
  services/logging/template.env
  services/monitoring/grafana/terraform/datasources.tf
Labels: observability, EPIC

#1182 ⚗️ upgrade distribution registry to v3.0.0, add tracing
  services/registry/docker-compose.yml.j2
  services/registry/template.env
Labels: observability, FAST

#1188 FluentD configuration: remove `/` in front of container names
  services/logging/fluentd/fluent.conf
Labels: FAST

#1190 Automatical lokal loki bucket creation
  services/logging/Makefile
  services/logging/template.env
Labels: t:enhancement, p:low-prio, t:infra-ops, refactoring
