Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2025-01, with the labels that each got.

#911 Fix: Varia, Cleanup
  scripts/common.Makefile
  scripts/deployments/deploy_everything_locally.bash
  services/maintenance-page/Makefile
  services/monitoring/Makefile
  services/monitoring/docker-compose.yml.j2
  services/monitoring/grafana-image-renderer/README.md
  services/monitoring/grafana-image-renderer/config.json
  services/monitoring/grafana/template-config.monitoring
  services/redis-commander/Makefile
  services/registry/Makefile
  services/simcore/Makefile
  services/traefik/Makefile
  services/vendors/Makefile
Labels: t:enhancement, FAST

#914 Remove env EC2_INSTANCES_ALLOWED_TYPES from special handling
  scripts/deployments/compose_stack_yml.bash
  services/simcore/envsubst_escape_dollar_sign.py
Labels: p:mid-prio

#925 Traefik: introduce domain redirect (1st version)
  services/traefik/docker-compose.yml.j2
  services/traefik/j2cli_customization.py
  services/traefik/template.env
Labels: p:high-prio

#929 Fix pre-commit step in CI
  .github/workflows/ci.yml
  .pre-commit-config.yaml
Labels: p:high-prio, FAST

#933 Add manual to traefik redirect capture all rule
  services/traefik/j2cli_customization.py
Labels: t:bug, p:mid-prio

#952 Introduce rolling docker config / secret update concept :tada: :rocket:
  scripts/common.Makefile
  scripts/j2cli_global_filters.py
  services/appmotion_gateway/.gitignore
  services/appmotion_gateway/Makefile
  services/appmotion_gateway/docker-compose.yml.j2
  services/appmotion_gateway/template.env
Labels: t:enhancement

#953 Update traefik router hardcoded priorities
  services/admin-panels/docker-compose.yml.j2
  services/registry/docker-compose.yml.j2
  services/simcore/docker-compose.yml
Labels: t:enhancement

#957 Configure redis replicas via ENV
  services/simcore/docker-compose.deploy.local.yml
  services/simcore/docker-compose.yml
Labels: t:enhancement
