Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2025-02, with the labels that each got.

#959 Filestash: remove special docker node label
  services/filestash/Makefile
  services/filestash/docker-compose.aws.yml
  services/filestash/docker-compose.dalco.yml
  services/filestash/docker-compose.master.yml
  services/filestash/docker-compose.yml
Labels: t:enhancement

#967 💄 minor: Change DNS Server to Quad9
  services/admin-panels/docker-compose.aws.yml
  services/adminer/docker-compose.aws.yml
  services/appmotion_gateway/docker-compose.aws.yml
  services/filestash/docker-compose.aws.yml
  services/graylog/docker-compose.aws.yml
  services/jaeger/docker-compose.aws.yml
  services/monitoring/docker-compose.aws.yml
  services/monitoring/docker-compose.dalco.yml
  services/monitoring/docker-compose.public.yml
  services/portainer/docker-compose.aws.yml
  services/registry/docker-compose.aws.yml
  services/traefik/docker-compose.aws.yml
  services/traefik/docker-compose.public.yml
Labels: p:low-prio

#968 Storage on master: single replica until storage is again able to.
  services/simcore/docker-compose.deploy.master.yml
Labels: FAST

#972 Remove docker api proxy from validate simcore settings
  scripts/deployments/validate_simcore_stack_yml.bash
Labels: t:bug, FAST
