Repository ITISFoundation/osparc-ops-environments, pull requests merged in 2025-03, with the labels that each got.

#976 Seperate dalco-staging: disable redis special handling
  services/filestash/template.env
  services/monitoring/docker-compose.yml.j2
  services/monitoring/pgsql_query_exporter_config.yaml.j2
  services/monitoring/template.env
  services/redis-commander/README.md
  services/redis-commander/config.json.j2
  services/redis-commander/template.env
  services/simcore/docker-compose.deploy.dalco.yml
  services/traefik/docker-compose.dalco.yml
  services/traefik/docker-compose.master.yml
Labels: t:enhancement, t:infra-ops

#983 Fix postgres router
  services/simcore/docker-compose.deploy.local.yml
  services/simcore/docker-compose.deploy.master.yml
  services/traefik/docker-compose.local.yml
Labels: t:bug

#988 Fix redis exporter environment
  services/monitoring/docker-compose.yml.j2
  services/monitoring/template.env
Labels: t:bug

#994 [PR Template] Service is monitored and testing URL
  .github/PULL_REQUEST_TEMPLATE.md
Labels: t:enhancement

#997 Registry: run on OPS nodes
  services/registry/docker-compose.yml.j2
Labels: FAST

#1001 Remove override storage replicas for master
  services/simcore/docker-compose.deploy.master.yml
Labels: t:bug
